"""Request-id correlation + structured logging + a CORS-safe error boundary.

Two jobs:

1. Give every request an id (`X-Request-ID`, echoed back, woven into logs) so a
   line in the logs can be tied to the response a developer saw.

2. Catch unhandled exceptions *inside* the CORS layer and turn them into the
   standard error envelope. FastAPI's default 500 is generated by an outer
   middleware that runs OUTSIDE CORSMiddleware, so the browser sees a misleading
   "CORS header missing" instead of the real error. Handling them here means the
   500 flows back out through CORS and carries the right headers + request id.
"""

import logging

from fastapi import FastAPI, Request
from starlette.responses import JSONResponse, Response

from app.core.context import get_request_id, new_request_id, reset_request_id, set_request_id
from app.core.errors import ErrorCode, build_error_body

logger = logging.getLogger("kiwi.request")


class _RequestIdFilter(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool:
        record.request_id = get_request_id()
        return True


def configure_logging(level: int = logging.INFO) -> None:
    """Structured-ish root logging that includes the request id on every line."""
    handler = logging.StreamHandler()
    handler.setFormatter(
        logging.Formatter(
            "%(asctime)s %(levelname)-7s %(name)s [rid=%(request_id)s] %(message)s",
            datefmt="%Y-%m-%dT%H:%M:%S%z",
        )
    )
    handler.addFilter(_RequestIdFilter())
    root = logging.getLogger()
    root.handlers = [handler]
    root.setLevel(level)


def add_request_context_middleware(app: FastAPI) -> None:
    """Add request-id + the CORS-safe error boundary.

    IMPORTANT: this must be registered so it sits *inside* CORSMiddleware (i.e.
    added before CORS in main.py), so the responses it returns still pass through
    CORS and pick up the access-control headers.
    """

    @app.middleware("http")
    async def request_context(request: Request, call_next):
        rid = request.headers.get("x-request-id") or new_request_id()
        request.state.request_id = rid
        token = set_request_id(rid)
        try:
            response: Response = await call_next(request)
        except Exception:
            logger.exception("Unhandled error on %s %s", request.method, request.url.path)
            response = JSONResponse(
                status_code=500,
                content=build_error_body(
                    ErrorCode.internal_error.value, "Internal server error"
                ),
            )
        finally:
            reset_request_id(token)
        response.headers["X-Request-ID"] = rid
        return response
